### ISSUE TITLE
Remove avahi-daemon from (debian) image

### ISSUE THREAD

**Issue by roeles** [hor63/horOpenVario#10]
Debian images have avahi-daemon running by default. It takes up some CPU, but I don't think anything needs it.
I suggest we remove it from images.

**Comment by hor63** [comment]
How much CPU is eaten up by the avahi-demon? Does it impact the OpenVario performance?
Since XCSoar on a Cubie uses ~10% CPU it should not be an undue additional load.

Its purpose is zero-config networking.
It allows finding your machine in an un-managed local network, e.g. an ad-hoc WiFi hotspot under the logical name `hostname.local`. Otherwise identifying the Cubie in a network by the IP address can be searching a needle in a haystack.
Particularly when the display is (not yet) working you can connect with ssh from another machine, and analyze logs, and modify settings directly, or switch the device tree to support a different panel, or HDMI. In this case you want  to find the OV on the network without searching the IP addresses of your subnet.

I recommend to disable the demon when you put the OV in operation, and do not need the feature.

**Comment by roeles** [comment]
It doesn't use that much. On my system I measure about 0.3% CPU all the time and 0.2% Memory usage.
It was more of a suggestion than anything else. I can see the use cases for it, but I happen to not use it.
